### PR TITLE
Close #184: support extended multiplexing for dbc export

### LINKED ISSUE #184: Extended multiplexing dbc dump
I observed the following effect and would like to discuss whether it is intended or not:

1. import a dbc that uses extended multiplexing
2. dump it to a new file (after applying some changes, not relevant for the multiplexing aspect)
3. open the new file with a dbc editor (I use that one from a well known company in Stuttgart …)
-->  much of the multiplexing info is missing, and therefore many conflicts are reported (overlapping signals …).

I inspected the dumped dbc file and found out that there's no section ```SG_MUL_VAL_```.
That section seems to be mandatory when using extended multiplexing.
Extended multiplexing has two aspects:
* allows more than one multiplexer signal within the same message
* allows assigning more than one multiplexer value to the same signal
The section ```SG_MUL_VAL_``` has to be used even if only one of these aspects apply.

Extending a dump for that section is not a big effort, I already have prepared it for my porpuses.
But I'm interested in other users opinion, especially in the possibilities or restrictions. E. g.:
* How to decide if database allows extended multiplexing (the internal help of my dbc editor says 'for J1939' and some others protocols, but not for a "normal CAN extended" dbc.
* Are there any interferences with other database formats? ```cantools``` supports different database formats, but I've been using dbc only so far ...

### PR DESCRIPTION
**Pull request by geo4711**
This PR support export of dbc with extended multiplexing. This is applied only if necessary, i. e. if at least one of the following items is fulfilled:
- a message has more than one multiplexer signals
- a signal is multiplexed by more than one multiplexer values

### CODE REVIEW

**Comment by geo4711** [comment]
Hi!
I'm not familiar with AppVeyor. It tells me that the build process with Python 3.8 failed due to communication problems with github:
image
I'm not sure if I can solve this problem by myself (or if it es caused by my PR).
Could you have a look at it, please?

**Comment by eerimoq** [comment]
I re-ran it. Now it passed.

**Comment by eerimoq** [comment]
Let's add the DBC dump assertion at the end of the already existing multiplex tests (test?multiplex, test_multiplex_choices and test_multiplex_2). If the new dump code needs additional testing we add more tests (I guess one or more of those you wrote in this PR). Add *_dumped.dbc if necessary as the dump function may reorder some lines.

**Comment by geo4711** [comment]
Thanks for re-running the build!
I've just added your proposal on my local repo (adding dump assertion to existing tests). There are two issues:
* multiplex_2.dbc results in an invalid dump (same with the version before this PR) --> I suggest to solve this separately. I haven't investigated the route cause yet; maybe three sub issues regarding the following line:
```SIG_VALTYPE_ 201588478 S9 : 1;BA_DEF_ BO_  "TpJ1939VarDlc" ENUM  "No","Yes";```
  * #186 (SIG_VALTYPE with extended frame ids)
  * missing line break
  * section SIG_VALTYPE should be below BA sections, not before (at least the original file multiplex_2.dbc is coded like that, and when I manually adapt the dumped one it works again).
* The dump creates some redundant lines in the mux section. I. e. if one message needs lines in the mux section, ALL muxed signales are listed their. The specification I have for dbc format does not explicitly tell you how to deal with that. I have tolerated that because ...
  * the redundant info is tolerated (by cantools as well as Vector's CANdb++)
  * the previous version of cantools doesn't dump the mux section at all (i. e. it leads to loss of information)
  * I wanted to keep the code flat. But that's maybe a quite weak argument ;-) and maybe it's better to get that fixed with a couple of extra lines ...

Here's just a snapshot showing the differences in the mux section (left = multiplex_2.dbc, right = dumped version):
image

What do you think about these issues?

**Comment by eerimoq** [comment]
I'll merge and probably make some modifications myself after the merge. Thanks for the PR =)

**Comment by geo4711** [comment]
Sounds great. Thanks :-)

**Pull request merged**
