### PR TITLE
Dbc allow plus in sig def

### PR DESCRIPTION
**Pull request by geo4711**
Some DBC generators use an extra '+' for defining the ranges of signals. This PR allows/tolerates this extra char.

### CODE REVIEW

**Comment by eerimoq** [comment]
Thanks. Looks good. Will merge once a test is in place.

**Comment by geo4711** [comment]
Sure. Just added a test and a separate DBC for that. But I'm still wondering how that change leads to reduced coverage ...

**Comment by eerimoq** [comment]
It's probably a bug in coveralls, so it's ok.

**Comment by eerimoq** [comment]
Now available on PyPI.

**Pull request merged**
