### PR TITLE
fixed minor bug in dbc file generation for multiplexing

### PR DESCRIPTION
**Pull request by kartikarcot**
This is in reference to issue #323. I do not know what kind of tests would be suitable for this since I am myself beginning to learn about CAN and DBC. I also do not have access to Vector Tools. Let me know how to go about it @eerimoq

### CODE REVIEW

**Comment by juleq** [comment]
Have you checked that multiplexer_signal indeed does contain a signal object and not just a signal name?

I do not have the time to go into the details but the failing tests leave the impression that
1.) this is already covered by tests and
2.) these tests are now failing because it already was a signal name.

You could step through with the python debugger to see whats going on. I would propose just loading and dumping a dbc again and break on the line that you have changed to inspect the contents of multiplexer_signal.

If you find it to be a name already I'd say that changing the misleading name to "multiplexer_name" or "multiplexer_signal_name" might be the only thing left to propose.

**Comment by kartikarcot** [comment]
Yea looks like this is due to a misunderstanding on my part. I interpreted your documentation about `multiplexer_signal` argument in the Signal constructor call to expect an object, whereas I see that you pass strings instead. Could be a better idea to pass the object since there would be consistency of name.

**Comment by andlaus** [comment]
@kartikarcot: is this PR still relevant? i.e. is the current behavior wrong and we should wait for you to fix the tests or ought this PR to be closed?

**Comment by juleq** [comment]
I´d say this was just a naming confusion. Will close for now. If anyone desires to rename to e.g. multiplexer_signal_name, this PR can be reopened.

**Pull request closed without merging**
