### PR TITLE
Parse recursively ARXML file in case of nested AR-PACKAGES

### PR DESCRIPTION
**Pull request by anxuae**
Hi,

I'm facing to a parsing issue for ARXML files. I have multiple nested AR-PACKAGES in my file.
This is a fix to introduce recursive search.

anxuae

### CODE REVIEW

**Comment by eerimoq** [comment]
Hello!

Does the ARXML specifications allow/recommend recursive search, or is this just a quick workaround to make your specific case to work? It would be nice to follow the idea outlined in the specs. =)

**Comment by anxuae** [comment]
Hello @eerimoq ,

Even if not popular, this is more common in ARXML for ECU connected to several buses.
The AUTO car specification authorize it, sub-package creation is authorized by the API: see https://autosar.readthedocs.io/en/latest/autosar4_api/package.html#ar4-package-package-createsubpackage

Best regards.
anxuae

**Comment by anxuae** [comment]
Hello,

I found this library https://github.com/ebroecker/canmatrix which seems to be able to parse recursively AR-PACKAGES. . Thus I will use it if you think that this PR is not acceptable.

BR
Antoine

**Comment by eerimoq** [comment]
I think that's a good idea. Leave the PR open to remind me that this functionality is requested. Thanks.

**Comment by andlaus** [comment]
after #263, this PR is hopefully not required anymore. I'll close it for now...

**Pull request closed without merging**
