### PR TITLE
Dev add device class

### PR DESCRIPTION
**Pull request by sgnes**
Hello,

Please check this change, ref to issue #120 .

### CODE REVIEW

**Comment by sgnes** [comment]
I will change it later to remove the change for message class, also I will create test case later .

**Comment by sgnes** [comment]
@eerimoq, would you please tell me why my new added device.py has 0% coverage, I tested it locally, and I have 100%.

**Comment by eerimoq** [comment]
Hello!

Thanks for the effort, but I'm not really sure whether this is useful or not. What is you use case? Can you give an example of when this functionality is needed? I just want to make sure not to add too much code that is seldom (or never) used. There is already the tester class that probably no one uses.

**Comment by sgnes** [comment]
For some test , we need to know the signal vlaue on the can bus, and also send aspecific signal  value to check the action of the tested ecu. With this interface it will be easier.
For now this works with normal message, but as no tp is used, not working with message bigger than 8bytes.

**Comment by eerimoq** [comment]
Did you try using the [tester class](https://github.com/eerimoq/cantools/blob/master/cantools/tester.py)?

**Comment by sgnes** [comment]
Seems has the similar functionality, i will try it.

**Pull request closed without merging**
