### PR TITLE
Initial value calculation according to Vector CANdb++

### PR DESCRIPTION
**Pull request by TheGreatChris**
Bugfix for issue described here: https://github.com/eerimoq/cantools/issues/251

### CODE REVIEW

**Review by andlaus — APPROVED** [review]
looks good to me. (I'm always a bit confused when the physical and when the "raw" value ought to be stored in the database...)

**Comment by s3bastiand** [comment]
Hi, I have tried the fix and it only partially worked for me. I encountered a new issue after I have applied it:
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float' "cantools"

Change the same line to:
initial_sig_values[signal.name] = (decimal.Decimal(signal.initial) * decimal.Decimal(signal.scale)) + decimal.Decimal(signal.offset)

solved my problem, but I'm not sure it's correct...

**Comment by juleq** [comment]
I have not looked into the details but I noticed the following:

1.) The signal class has an (optional) copy of min/max/scale/offset as decimal type for lossless calculations.

2.) You could inspect utils.py to understand the handling there:
’’’
def _encode_field(field, data, scaling)
’’’

**Comment by TheGreatChris** [comment]
> 
> 
> Hi, I have tried the fix and it only partially worked for me. I encountered a new issue after I have applied it:
> TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float' "cantools"
> 
> Change the same line to:
> initial_sig_values[signal.name] = (decimal.Decimal(signal.initial) * decimal.Decimal(signal.scale)) + decimal.Decimal(signal.offset)
> 
> solved my problem, but I'm not sure it's correct...

Please elaborate a bit more how the signal definition looks of the DBC that produced your described error. I can't reproduce the issue and neither can I fully comprehend the decimal classes supposed usage.

**Comment by TheGreatChris** [comment]
I could do a bit of debugging and I was able reproduce the issue:
initial is always of type Decimal while scale and offset is of type float.
It seems that Decimal class only fails to multiply certain floats. I guess if the float can't be converted into a Decimal. For example Decimal('1') * 100 will work but Decimal('1') * 0.1 will fail.
I agree with s3bastiand's proposal to convert offset and scale to a Decimal before doing init value calculation.

**Comment by TheGreatChris** [comment]
Using already present decimal values for lossless calculations as mentioned by @juleq.

**Comment by juleq** [comment]
Looking good. Thank you for fixing this, @TheGreatChris.

**Pull request merged**
