### PR TITLE
ARXML: fix determining signal lengths their initial value and its range

### PR DESCRIPTION
**Pull request by andlaus**
This PR continues the quest for ARXML-3 support, cf https://github.com/andlaus/cantools/tree/arxml_refactor

This PR adds support for determining the length of a given signal via the system signal if the length is not specified by the i-signal itself (first patch),  it corrects determining the possible range of signals (second patch; the possible value range of the signal is the range over all COMPU-SCALEs, not just the first one)  and it implements loading the initial value of signals (third patch).

The next PR will contain the changes for the differences between ARXML-3 and ARXML-4.

Andreas Lauser <andreas.lauser@mbition.io>, Mercedes-Benz AG on behalf of [MBition GmbH](https://mbition.io/).

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)

### CODE REVIEW

**Comment by eerimoq** [comment]
No tests needed?

**Comment by andlaus** [comment]
as usual, coverage results are strange, but this time in a different sense: there's a significant regression in `arxml.py'. I'll fix that tomorrow...

**Comment by andlaus** [comment]
> No tests needed?

actually, there are, but I screwed up a bit: I put the these tests into the patch for autosar 3 (next PR) and surgically separated these patches later, while not adding proper tests for this to the existing AR4 infrastucture. sorry for the mess, I'll fix it ASAP.

**Comment by eerimoq** [comment]
Great work overall!

**Comment by eerimoq** [comment]
Btw, which features in cantools are Daimler using?

**Comment by eerimoq** [comment]
@andlaus Any updates?

**Comment by koppor** [comment]
I think, the fixing took longer. Because of other work, it will probably be mid-January until a follow-up. Sorry for the delay.

Oliver Kopp <oliver.kopp@mbition.io>, Mercedes-Benz AG on behalf of [MBition GmbH](https://mbition.io/).

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md#mbition-gmbh)

**Comment by eerimoq** [comment]
Ok!

**Comment by andlaus** [comment]
ok, I finally managed update this. Note that I'm not 100% sure if determining the initial value of signals is correct (it is certainly not complete because it only includes the saner ways), but at least the `system-4.2.arxml` file still passes the XSD for autosar 4.3 (after changing the namespace).

**Comment by andlaus** [comment]
@eerimoq : I guess this PR is ready to go in. I have no idea where the huge drop in coverage asserted by coveralls is supposed to come from: the PR only touches `arxml.py` when it comes to relevant files and that one has basically only a few error additional error cases uncovered which -- according to coveralls -- constitute 0.77% of the source code of that file.

**Comment by andlaus** [comment]
> Btw, which features in cantools are Daimler using?

I can't speak for Daimler as a whole, but I personally use it to read the bus description files for various vehicles. Once the database object is read, it depends on the concrete application: sometimes I need to generate C++ code to decode frames, convert the descriptions to some simpler formats (like e.g. DBC) and sometimes I use the decoded data directly in python for some calculations. Overall I'm quite impressed by the overall code quality of cantools :)

**Pull request merged**
