### PR TITLE
Fix: comment handling for database in dbc format

### PR DESCRIPTION
**Pull request by malneni**
Updated dbc.py to handle comment for Bus.
For comment  Sequence after CM_ is choice.  ex: CM_ "MyBus";

### CODE REVIEW

**Comment by eerimoq** [comment]
Hello and thanks for the contribution. Looks useful. Please add test case(s) of the new functionality, and then I'll review.

**Comment by malneni** [comment]
I have difficulty in running tests. I edited vehicle.dbc to add a comment & run test_database but I get errors of file not found
FileNotFoundError: [Errno 2] No such file or directory: 'tests/files/dbc/vehicle.dbc'.

I do not know if i am doing something wrong or If there is problem with my python installation. I need time to check it. Thanks

**Comment by eerimoq** [comment]
Just run "python3 setup.py test" in the root of the repository.

**Comment by malneni** [comment]
I will create new pull request with updated code. I am not good with multiple commits, So I will create new pull request with single commit and test cases

**Pull request closed without merging**
