### PR TITLE
Mostly dbc file fixes.

### PR DESCRIPTION
**Pull request by juleq**
- Fixed dbc files. All of them open now in CANdb++. 
- File foobar.dbc now contains a valid CAN FD configuration.
- Fixed issue in enum attribute handling: DEF_DEF use the symbol while DEF_ and the attribute use the ENUM index.
- Added .ini files in test folder to gitignore.

### CODE REVIEW

**Comment by juleq** [comment]
I am now sure why the aready merged commits also show up here.

I have synced my fork, merged and pushed it here. I did:
- add and commit
- fetch upstream
- merge upstream/master
- resolved conflicts
- add and commit
- push origin master
- PR

**Comment by eerimoq** [comment]
All commits in you previous PR was squashed into one before merged. All these commits are still present in your fork. If you commit your changes directly on top of eerimoq/cantools/master the commits from the previous PR will not show in this PR.

**Comment by eerimoq** [comment]
Does CANdb++ only support Windows line endings ("\r\n")?

**Comment by juleq** [comment]
It opens \n, too. But saving will completely rewrite using \r\n...

**Comment by eerimoq** [comment]
Ok!

My computer is running Linux which makes the default file ending is \n. I'll make sure to use \r\n in DBC-files, but in .py-files I prefer \n as I am on a Linux machine. Is it possible for you to do that as well? =)

**Comment by juleq** [comment]
Sure. I think my editor might have workspace settings for that. I thought this issue has been solved by git? I guess one needs to configure the repo accordingly...

**Comment by juleq** [comment]
Maybe that can ease our pain:
https://help.github.com/articles/dealing-with-line-endings/
:)...
One for the repo with exclusions for dbc files...

**Comment by eerimoq** [comment]
Looks promising. Can you add a .gitattributes file and we'll find out how it works out?

**Comment by juleq** [comment]
By the way. Are you aware of this project? Is seems to have a quite extensive dbc writer...

https://github.com/aheit/cantools/blob/master/src/libcandbc/dbcwriter.c

**Comment by eerimoq** [comment]
I've seen that the project exists, but I've not looked into its implementation, no.

**Comment by eerimoq** [comment]
Would be nice if you could create a new PR without all the commits =)

**Comment by juleq** [comment]
I thought I did correctly. What do I need to do? Rebase or something?

**Comment by eerimoq** [comment]
You could create a new branch locally on your PC based on upstream/master, and then apply your changes and commit. Then submit a PR to this repositories master branch.

**Comment by juleq** [comment]
Ok. Thanks. I‘ll do that tomorrow.

**Pull request closed without merging**
