### PR TITLE
Use ArgumentDefaultsHelpFormatter to show defaults in --help

### PR DESCRIPTION
**Pull request by altendky**
It is often nice to have CLI --help output include the default values for parameters that have a default.  `argparse` provides `argparse.ArgumentDefaultsHelpFormatter` to do this automatically.  This provides consistent presentation of the defaults without manual intervention for each parameter or continued maintenance keeping the help text inline with the actual operational code.

### CODE REVIEW

**Comment by eerimoq** [comment]
Hmm, this might be good, but I prefer the flexibility of formatting the help text freely instead.

**Comment by altendky** [comment]
Talk about maintenance hassle...

**Review by andlaus — COMMENTED** [review]
Please resolve the merge conflict (due to the #283, sorry) and add a meaningful description of what the patch does. With that I am in favor of merging it.

**Comment by altendky** [comment]
@andlaus, thanks for the interested.  If you meant you wanted a description added in the OP then that is done.  If you meant something else, let me know. `:]`

**Pull request merged**
