### PR TITLE
Decoding of candump log format

### PR DESCRIPTION
**Pull request by AxelVoitier**
Hello,

This adds support for decoding of candump log format in the CLI.

Cheers,
Axel

### CODE REVIEW

**Comment by eerimoq** [comment]
Hi!

Just curious, what's the benefit of supporting this log format as well?

/ Erik

**Comment by AxelVoitier** [comment]
Hello,

You don't always control the source of dump.
Sometimes it is someone else sending you the dump captured on their own system, and they used the -l or -L flag on candump.
Alternative is to "reformat" it, eg. by replaying the dump with canplayer and recapturing it locally. But if the decode tool can do it directly it is much simpler.


Cheers,
Axel

**Comment by eerimoq** [comment]
Ok, sounds fair.

Not sure, but maybe the decode command should automatically detect the log format? Should be easy to implement and improve the user experience.

**Comment by AxelVoitier** [comment]
I though about that but did not wanted to complicate it much. I can give it a try.

**Comment by AxelVoitier** [comment]
Done

**Comment by eerimoq** [comment]
That was quick! Looks good, merging.

**Comment by eerimoq** [comment]
Released to PyPI. Version 35.1.0.

**Comment by AxelVoitier** [comment]
Neat! Thanks

**Comment by eerimoq** [comment]
:P

**Pull request merged**
