### PR TITLE
Stop C struct unpacking from erasing existing data

### PR DESCRIPTION
**Pull request by basketofkittens**
Remove memset call for unpack functions. Add logic to assign buffer value to first occurrence of a signal. Remaining occurrences of same signals are immediate-ORed as previously.

Discussion ref: https://github.com/eerimoq/cantools/issues/193

Unable to run `make test` locally. It terminates with `make: *** [test] Error 36`. Seems to be a MacOS-ism.

### CODE REVIEW

**Comment by eerimoq** [comment]
Looks like `dst_p` must be void-casted when unused.

**Comment by eerimoq** [comment]
Any progress?

**Comment by basketofkittens** [comment]
@eerimoq I haven't forgotten about this. I just started a new job, so I haven't had much time for personal projects lately. I'll take a crack at it this weekend.

**Comment by eerimoq** [comment]
Ok, great! Looking forward to merging this :)

**Comment by eerimoq** [comment]
Something similar to this is now implemented on master and part of release 34.0.0.

**Pull request closed without merging**
