### PR TITLE
Update db.py

### PR DESCRIPTION
**Pull request by vfdev-5**
Hi, 
a small modification to avoid IndexError if 'BU_' field is empty in the DBC file. 
What do you think ?

### CODE REVIEW

**Comment by eerimoq** [comment]
I merged a pull request today which should fix this issue. Please install release 2.0.0 from PyPi and close this pull request if it works.

Upgrade cantools with: `pip install -U cantools`

**Comment by vfdev-5** [comment]
I think I was too fast with some renamings. My fault, sorry. There's a typo in the code. Happily you travisci reveals this.

**Comment by eerimoq** [comment]
The newly created release should support an empty BU_ field. Install it and we'll close this pull request if it works.

**Comment by vfdev-5** [comment]
I'll check your new code and close the PR if it is Ok

**Pull request closed without merging**
