### PR TITLE
File ext ignore case

### LINKED ISSUE #165: load database requires lower case file extension
The following command throws an exception:
`dbc = cantools.database.load_file("dummy.DBC")`

...
`ValueError: expected database format 'arxml', 'dbc', 'kcd', 'sym', 'cdd' or None, but got 'DBC'`

When calling the method with lower case file extension (.dbc) everything is fine.
It seems to be irrelevant if the file's extension itself uses upper or lower case, it's just the "filter" in the load_file method.

Hint: For manual use it's no problem to use lower case. But searching for files with glob.glob(...) could return mixed results which then have to be enforced to lower case names.

### PR DESCRIPTION
**Pull request by geo4711**
Closes #165 --> accept database file extension both upper case/lower case/any combination

### CODE REVIEW

**Comment by eerimoq** [comment]
Lot's of tests are failing. Please investigate why and take action based on that.

**Comment by eerimoq** [comment]
Please add a test case and I can merge.

**Comment by geo4711** [comment]
thanks a lot for your patience and advice :-)

**Comment by eerimoq** [comment]
The documentation here should be updated to match the current implementation. I suggest to write that both lower and upper case file extensions are allowed instead of adding upper case extensions to the table, but it's up to you. Mixing upper and lower case in the same extension is probably not worth mentioning.

https://github.com/eerimoq/cantools/blob/master/cantools/database/__init__.py#L106-L124

**Comment by eerimoq** [comment]
Add *.DBC to MANIFEST.in. Otherwise the new file is not part of the release and the test using it will fail.

**Pull request merged**
