### PR TITLE
Misprint fix in docs URL

### PR DESCRIPTION
**Pull request by manul7**

### CODE REVIEW

**Comment by eerimoq** [comment]
I had the same issue in another project, and solved it by changing the link to the form `http://cantools.readthedocs.org`. I suggest that we do the same here.

**Comment by manul7** [comment]
@eerimoq seems that the root cause of broken link issue is missing "/" at the end of URL, but as link to "readthedocs.org" will be redirected to "readthedocs.io" I decided to change top-level domain name too. If it's unacceptable, I'll leave ".org".

**Comment by eerimoq** [comment]
Ok, let's change to `.io`.

**Comment by eerimoq** [comment]
I updated the link, thanks!

**Pull request closed without merging**
